language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-20.0.0

    # The SDK version used to compile your project
    - android-20

    # Additional components
	- extra

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-20
    #- sys-img-x86-android-17
jdk: oraclejdk7
before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi

script:
  - ./gradlew clean build
